-ifndef(ERRCODE_HRL).
-define(ERRCODE_HRL, true).

-define(ERROR, 0).
-define(ERROR_ROOM_FULL, 1).
-define(ERROR_ROOM_NOT_EXIST, 2).
-define(ERROR_PLAYER_IN_ROOM, 3).
-define(ERROR_PLAYER_NOT_IN_ROOM, 4).
-define(ERROR_FIGHT_DIE_PLAYER_USE_SKILL, 5).
-define(ERROR_FIGHT_PLAYER_OP_NOT_IN_WAIT, 6).
-define(ERROR_FIGHT_PLAYER_OP_NOT_ELLEGAL, 7).
-define(ERROR_FIGHT_NV_OP, 8).
-define(ERROR_FIGHT_XUANJU_JINGZHANG_OP, 9).
-define(ERROR_FIGHT_DIE_SKILL_1, 10).
-define(ERROR_FIGHT_DIE_SKILL_2, 11).
-define(FRIEND_TOO_MUCH, 19001).

-endif.

